spring:
  profiles:
    active: prod
  datasource:
    platform: prod
    initialization-mode: always
    url: jdbc:postgresql://localhost:5432/bookcardDB 
    username: scribe 
    password: scribe 
  jpa:
    hibernate:
      ddl-auto: none    
  shell:
    interactive:
      enabled: true      

application: 
  fetchsize: 5